### ISSUE TITLE
Font size of food name is very small

### ISSUE THREAD

**Issue by nuess0r** [AYCE-earth/public#2]
I've got the poster printed on paper from the wemakeit campaign. Even in the original 70x100 size the food names are very small and I have to come quite close to the poster to read it.

The 70x100 format is too big to hang up in our flat, so I hoped that I can find in this repo a version that is rendered/optimized for A2 format (that would fit in our kitchen) meaning that the text is not smaller on the A2 than on the 70x100 (if I would print the original PDF on A2 I would need a magnifier glass).

Thanks for the very interesting work, it will definitely influence my menu planning.

**Comment by mklarmann** [comment]
I was thinking about the same thing. A2 (594 x 420 mm) would fit on the fridge (in CH they are 45cm wide - in Germany a bit bigger). The font would need to be 66% bigger then. I created a new Sketch file for it. But it will take quite some while to reposition a lot of of icons again. See here: 
[A3.pdf](https://github.com/AYCE-earth/public/files/6089818/A3.pdf)

**Comment by mklarmann** [comment]
The new release contains a new size with bigger fonts: https://github.com/AYCE-earth/public/releases
Our fridge is actually 59cm wide - so A1 or B2 should also work...
