### ISSUE TITLE
Units in the poster

### ISSUE THREAD

**Issue by Mathias70** [AYCE-earth/public#6]
I have download the poster and like it very much. But why this complicated units. In my eyes it makes no sense to calculate it in an amount of product for 1/3 daily consumption. It would be more easy to have it in per kg or liter. Because I never will eat 1.4kg onions a day or 2.2kg vinegar. And why is the table at the second page not in order of the names? It is very complicated to find something,

**Comment by mklarmann** [comment]
Hey Mathias

Thank you for your comment. 
Liter / kg does not allow for a fair comparison between ingredients. One liter of water is not the same as 1kg of beef in terms of nutrients it provides us.

You can find more info about this methodology here: https://github.com/Eaternity/eaternity-website/wiki/What-products-or-recipes-are-climate-friendly%3F-How-to-define-a-goal.

Does this make sense for you?

Best regards,
Manuel

**Comment by mklarmann** [comment]
The documentation was update to recent version here: http://eaternity.notion.site
