### ISSUE TITLE
Vegetable broth issues

### ISSUE THREAD

**Issue by stellingsimon** [AYCE-earth/public#7]
First of all, thank you for this amazing poster! What a beautiful gem for our fridge.

I spotted some very minor issues, all related to vegetable broth: 

1. Vegetable broth shows up twice on the "Radar". 
    1a. In all three PDFs of [release v1.6](https://github.com/AYCE-earth/public/releases/tag/v1.6), vegetable broth shows up below "Chicken broth" and again below "Salt".
    1b. (Probably no longer relevant: In all three PDFs of [release v1.5](https://github.com/AYCE-earth/public/releases/tag/v1.5), vegetable broth shows up below "Chicken broth" and again next to "Beef broth", with a different CO2e value.)
3. In the English version, the large table lists "Vegetable *stock*" (but uses *broth* in the radar), while "Beef broth" and "Chicken broth" are listed with the same names used in the radar.
4. In all languages, "Beef broth" and "Chicken broth" are grouped under "Beverages", but "Vegetable stock" is listed under "Seasonings", which seems slightly odd. In the radar, they are clustered with seasonings, so that's where I would expect to find them.

I tried to provide a PR to fix these, but kactus.io ships only for OS X and I failed to build it locally on my Linux box. Sorry :-(

**Comment by mklarmann** [comment]
Thanks for your help. I updated the posters. I hope I didn't miss anything : )

**Comment by stellingsimon** [comment]
Wow, that was fast. Thanks!
